spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
            scope: ${OAUTH_GOOGLE_SCOPE}
          naver:
            client-id: ${OAUTH_NAVER_CLIENT_ID}
            client-secret: ${OAUTH_NAVER_CLIENT_SECRET}
            redirect-uri: ${OAUTH_NAVER_REDIRECT_URI}
            authorization-grant-type: ${OAUTH_NAVER_GRANT_TYPE}
            scope: ${OAUTH_NAVER_SCOPE}
            client-name: ${OAUTH_NAVER_CLIENT_NAME}
        provider:
          naver:
            authorization-uri: ${OAUTH_NAVER_AUTH_URI}
            token-uri: ${OAUTH_NAVER_TOKEN_URI}
            user-info-uri: ${OAUTH_NAVER_USER_INFO_URI}
            user-name-attribute: ${OAUTH_NAVER_USER_NAME_ATTRIBUTE}
