spring:
  application:
    name: travelmate
  profiles:
    active: dev
    group:
      dev:
        - oauth
      prod:
        - oauth

server:
  servlet:
    encoding:
      force-response: true

thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML
  cache: false

logging:
  config: classpath:log4j2.yml
