spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 697889968185-amc5gbliqdru90admji75vgb3t3tee0u.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
          naver:
            client-id: MWdMoq4vuoyEBlO1FIFi
            client-secret: KyRuxkuF7g
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
