name: CD for Develop

on:
  push:
    branches:
      - chore/build-docs

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build \
            --build-arg ENV=develop \
            -t ${{ secrets.DOCKER_USERNAME }}/travelmate-api:develop .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/travelmate-api:develop